[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
node = "lts"
"npm:eslint" = "latest"
pipx = "latest"
prettier = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
usage = "latest"
